# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: SelfHostedPool

# Checkout the GitHub repo
steps:
- checkout: self

# Confirm the files from GitHub repo
- script: |
    echo "Checking files from GitHub repo:"
    ls -R $(Build.SourcesDirectory)
  displayName: 'List repo files'

# Upload files from GitHub repo to Azure Blob Storage
- task: AzureFileCopy@6
  displayName: 'Copy files from GitHub repo to Azure Blob Storage'
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/*' # All files from the GitHub repo
    azureSubscription: 'Nova' # Service connection name
    Destination: 'AzureBlob'
    storage: 'kamdevopsstr' # Storage account name
    ContainerName: 'kamcontainer' # Container name
    AdditionalArguments: '--log-level=DEBUG' # For detailed logs
    enableCopyPrerequisites: true
